
language: python

python:
 - "3.4"

sudo: required

install:   # Instalación de dependencias
  - sudo apt-get install python3-dev
  - pip3 install --upgrade pip
  - pip3 install Flask
  - pip3 install nose

script:
  - nosetests ./tests/test.py
