
language: python

python:
  - "2.7"
  - "3.4"

install:   # Instalación de dependencias
  - sudo apt-get install python-dev
  - pip install --upgrade pip
  - pip install Flask
  - pip install nose

script:
  - nosetests
